In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [58]:
tips_data = sns.load_dataset("tips")
tips_data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [59]:
y = tips_data.filter(["tip"])
x = tips_data.drop(["tip"],axis=1)

In [60]:
x.head()

total_bill     sex smoker  day    time  size
0       16.99  Female     No  Sun  Dinner     2
1       10.34    Male     No  Sun  Dinner     3
2       21.01    Male     No  Sun  Dinner     3
3       23.68    Male     No  Sun  Dinner     2
4       24.59  Female     No  Sun  Dinner     4

In [61]:
numrical = x.filter(["total_bill","size"])
numrical.head()

total_bill  size
0       16.99     2
1       10.34     3
2       21.01     3
3       23.68     2
4       24.59     4

In [62]:
catgorical = x.drop(["total_bill","size"],axis=1)
catgorical.head()

sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

In [63]:
cat_num = pd.get_dummies(catgorical,drop_first =True)
cat_num.head()

sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  time_Dinner
0           1          1        0        0        1            1
1           0          1        0        0        1            1
2           0          1        0        0        1            1
3           0          1        0        0        1            1
4           1          1        0        0        1            1

In [64]:
X = pd.concat([numrical,cat_num],axis=1)
X.head()

total_bill  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  \
0       16.99     2           1          1        0        0        1   
1       10.34     3           0          1        0        0        1   
2       21.01     3           0          1        0        0        1   
3       23.68     2           0          1        0        0        1   
4       24.59     4           1          1        0        0        1   

   time_Dinner  
0            1  
1            1  
2            1  
3            1  
4            1

In [65]:
y.head()

tip
0  1.01
1  1.66
2  3.50
3  3.31
4  3.61

In [66]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20 ,random_state = 0)

In [31]:

from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')


temperature = [32., np.nan, 28., np.nan, 32., np.nan, np.nan, 34., 40.]
windspeed  = [ 6.,  9., np.nan,  7., np.nan, np.nan, np.nan,  8., 12.]


n_arr_1 = np.array(temperature).reshape(3,3)
print('temperature:\n',n_arr_1)
n_arr_2 = np.array(windspeed).reshape(3,3)
print('windspeed:\n',n_arr_2)


imp.fit(n_arr_1)
imp.transform(n_arr_2)
#imp.fit_transform(n_arr_2)

temperature:
 [[32. nan 28.]
 [nan 32. nan]
 [nan 34. 40.]]
windspeed:
 [[ 6.  9. nan]
 [ 7. nan nan]
 [nan  8. 12.]]


array([[ 6.,  9., 34.],
       [ 7., 33., 34.],
       [32.,  8., 12.]])

In [34]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan,strategy="mean")
temperature = [32., np.nan, 28., np.nan, 32., np.nan, np.nan, 34., 40.]
windspeed  = [ 6.,  9., np.nan,  7., np.nan, np.nan, np.nan,  8., 12.]
arr1 = np.array(temperature).reshape(3,3)
arr2 = np.array(windspeed).reshape(3,3)
print(arr1)
print(arr2)
#imp.fit(arr1)
imp.fit_transform(arr2)

[[32. nan 28.]
 [nan 32. nan]
 [nan 34. 40.]]
[[ 6.  9. nan]
 [ 7. nan nan]
 [nan  8. 12.]]


array([[ 6. ,  9. , 12. ],
       [ 7. ,  8.5, 12. ],
       [ 6.5,  8. , 12. ]])

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [39]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
regressor = lin_reg.fit(X_train,y_train)
y_pred = regressor.predict(X_test)
y_pred

array([[2.75976768],
       [2.99712626],
       [2.81673204],
       [1.4632311 ],
       [3.12654885],
       [1.77482578],
       [2.54679105],
       [3.11359077],
       [2.88681115],
       [4.50140326],
       [3.18428659],
       [3.17091975],
       [2.3527022 ],
       [2.29224593],
       [2.87517409],
       [4.16944264],
       [1.92603957],
       [2.24308317],
       [2.3679374 ],
       [3.30322842],
       [3.79547836],
       [2.84290839],
       [2.5417152 ],
       [2.43574813],
       [2.32853543],
       [2.58333477],
       [2.76729999],
       [4.59978345],
       [3.73195325],
       [2.40199442],
       [2.31295548],
       [2.27962689],
       [2.46828159],
       [1.92661159],
       [2.71399481],
       [2.30185826],
       [2.71063603],
       [2.09555601],
       [5.60088215],
       [3.34295006],
       [2.25147162],
       [2.27534617],
       [2.56519997],
       [4.33905752],
       [2.11239476],
       [2.81768662],
       [2.60608807],
       [2.995

In [42]:
from sklearn import metrics
print ("Mean Absolute Error:",metrics.mean_absolute_error(y_test,y_pred))
print ("Mean Squared Error:" ,metrics.mean_squared_error(y_test,y_pred))
print ("Root Mean Squared Error:",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

Mean Absolute Error: 0.7080218832979829
Mean Squared Error: 0.893919522160961
Root Mean Squared Error: 0.9454731736865732


In [44]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=5)
regressor = knn_reg.fit(X_train , y_train)
y_pred = regressor.predict(X_test)
y_pred

array([[2.61 ],
       [3.214],
       [3.218],
       [2.444],
       [3.056],
       [2.66 ],
       [3.014],
       [2.536],
       [3.3  ],
       [4.5  ],
       [3.6  ],
       [2.494],
       [2.558],
       [2.836],
       [2.796],
       [4.606],
       [1.576],
       [2.416],
       [2.944],
       [3.2  ],
       [2.754],
       [2.544],
       [3.004],
       [2.558],
       [3.004],
       [2.746],
       [2.796],
       [4.958],
       [3.606],
       [2.544],
       [2.544],
       [2.012],
       [2.566],
       [2.496],
       [3.202],
       [2.426],
       [2.734],
       [1.576],
       [6.462],
       [3.206],
       [2.796],
       [2.012],
       [2.378],
       [4.312],
       [2.496],
       [2.436],
       [2.858],
       [3.22 ],
       [2.734]])

In [45]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))
print(metrics.mean_squared_error(y_test,y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

0.7513877551020406
0.9462902040816326
0.9727744877830794


In [49]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=42,n_estimators=500)
regressor =rf_reg.fit( X_train , y_train)
y_pred= regressor.predict( X_test)
# evaluating algorithm performance
from sklearn import metrics
print ('Mean Absolute Error:' ,metrics.mean_absolute_error(y_test , y_pred))
print ('Mean Squared Error:' ,metrics.mean_squared_error (y_test , y_pred))
print ('Root Mean Squared Error:' ,np.sqrt(metrics.mean_squared_error (y_test , y_pred)))

<ipython-input-49-9bc07b4ff931>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor =rf_reg.fit( X_train , y_train)


Mean Absolute Error: 0.7045665306122448
Mean Squared Error: 0.8020627395265322
Root Mean Squared Error: 0.8955795551074913


In [53]:
from sklearn import svm
svm_reg = svm.SVR()
regressor = svm_reg.fit( X_train , y_train)
y_pred= regressor.predict( X_test)
# evaluating algorithm performance
from sklearn import metrics
print ('Mean Absolute Error:' ,metrics.mean_absolute_error(y_test , y_pred))
print ('Mean Squared Error:' ,metrics.mean_squared_error (y_test , y_pred))
print ('Root Mean Squared Error:' ,np.sqrt(metrics.mean_squared_error (y_test , y_pred)))

Mean Absolute Error: 0.7362521512772694
Mean Squared Error: 0.9684825097223091
Root Mean Squared Error: 0.9841150896731078


C:\Users\best tech\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [56]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(regressor,X,y,cv=10,scoring="neg_mean_absolute_error"))

[-0.63597629 -0.64100806 -0.59205586 -0.54662674 -0.73001745 -0.56890409
 -0.68027131 -1.34683335 -0.90053741 -0.84072875]


C:\Users\best tech\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\best tech\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\best tech\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\best tech\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for